### ISSUE TITLE
Automate Inclusion of jpo-ode JAR Files in Dev Container Setup

### ISSUE THREAD

**Issue by dmccoystephenson** [Trihydro/TIM-Manager#2]
## Description
The required jpo-ode JAR files were removed from the repository due to GitHub storage limitations, but they are still essential for the dev container to function correctly. Currently, developers need to manually build these JARs and include them in the project before running the dev container.

This manual step adds friction to the development workflow. It would be preferable if the dev container had access to these JAR files without the need for user intervention.

### Using Git LFS
Git Large File Storage (LFS) offers a way to manage the jpo-ode JAR files efficiently, keeping them accessible without inflating the repository size. However, further investigation is necessary to ensure this method does not introduce additional costs or unexpected complications.

For more details, refer to the [Git LFS documentation](https://git-lfs.com/).

### Using Git Submodule in Dev Container Build
Incorporating the jpo-ode repository as a Git submodule and building the JAR files during container setup could be a viable solution.

### Cloning in Dev Container Build
The Dockerfile for the development container can be modified to clone the required source code and build the jpo-ode JAR files during container setup.

**Comment by dmccoystephenson** [comment]
Has this issue been addressed? @mwodahl

**Comment by mwodahl** [comment]
Yes, this is no longer an issue as we're using the USDOT jpo-ode images.
